test('GET /status should return status 200 with correct response', async () => {
  const response = await fetch('http://localhost:3000/api/v1/status')
  const data = await response.json()
  expect(response.status).toBe(200)
  const parsedDate = new Date(data.updated_at).toISOString()
  expect(data.updated_at).toEqual(parsedDate)
  expect(data.dependencies.database.max_connections).toEqual(100)
  expect(data.dependencies.database.bd_version).toEqual(16.2)
  expect(data.dependencies.database.opened_connections).toEqual(1)
})
